import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import App from './App'
import Header from '@/components/header'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <App />
        {/* <div className={styles.description}>
          <p>
          </p>
          <div>
          </div>
        </div>

        <div className={styles.center}>
          <div className={styles.thirteen}>
          </div>
        </div>

        <div className={styles.grid}> */}
          {/* <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a> 
        </div>
        */}
      </main>
    </>
  )
}
